name: Main Workflow

on:
  push:
    branches:
    - main
    tags:
    - 'v*.*.*'

jobs:
  main-job:
    name: Main Job
    permissions:
      id-token: write
      attestations: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: sudo ./utils/dependencies.sh

      - name: Setup vcpkg caching
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Build MEGAsync
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: ./utils/build.sh

      - name: Create AppImage
        run: ./utils/package.sh

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          subject-path: ./MEGAsync-x86_64.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage-artifact
          path: ./MEGAsync-x86_64.AppImage

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./MEGAsync-x86_64.AppImage
