name: Release

on:
  push:
    tags:
    - 'v[0-9].*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: ./dependencies.sh

      - name: Build MEGAsync
        run: ./build.sh

      - name: Create AppImage
        run: ./package.sh

      - name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload AppImage
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./MEGAsync-x86_64.AppImage
          asset_name: MEGAsync-x86_64.AppImage
          asset_content_type: application/octet-stream

      - name: Print URL
        run: |
          echo "Release: ${{ steps.create-release.outputs.html_url }}"
          echo "AppImage: ${{ steps.upload-release-asset.outputs.browser_download_url }}"
